services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U user -d mydata"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
  


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres



  webflask:
    build: ./flaskproj
    image: flask-back
    container_name: flsite
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:3228:4000"
    volumes:
      - ./flaskproj:/app


networks:
  dbnet:
    driver: bridge


volumes:
  postgres-data: