name: my-github-basics
env:
  APPLICATION_NAME: "flask-site"
  DEPLOY_PACKAGE_NAME: "flask-site-file-${{ github.sha }}"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world from test
      run: echo "hello world from test"
    - name: execute few commands
      run : |
        echo "hello world 1"
        echo "hello world 2"
        echo "Application name: ${{ env.APPLICATION_NAME}}"
    


  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: print hello world from deploy
      run: |
        echo "hello world from deploy"
        echo "Deploy package name: ${{ env.DEPLOY_PACKAGE_NAME }}"
    
